
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?
         useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    encoding: UTF-8
logging:
  level:
    root: info
    tech.turl: debug
  file:
    name: log/blog-dev.log

comment:
  avatar: /images/avatar.png
